=== ilievladiulian/driversed/src/main/resources/xml/scoalasoferi.dtd
<!ELEMENT scoalaSoferi (studenti, informatie)>
<!ELEMENT studenti (student*)>
<!ELEMENT student (nume, numarTelefon, sex, varsta, adresa, examen*, dataInscriere, categorie+, instructor)>
<!ELEMENT instructor (nume, numarTelefon, sex, varsta, adresa, masina)>
<!ELEMENT informatie (nume, dataDeschidere)>
<!ELEMENT examen (dataExamen, nota)>
<!ELEMENT masina (model, anFabricatie, culoare, tip)>
<!ELEMENT dataInscriere (#PCDATA)>
<!ELEMENT dataDeschidere (#PCDATA)>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT categorie (#PCDATA)>
<!ELEMENT numarTelefon (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT adresa (#PCDATA)>
<!ELEMENT dataExamen (#PCDATA)>
<!ELEMENT nota (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT anFabricatie (#PCDATA)>
<!ELEMENT culoare (#PCDATA)>
<!ELEMENT tip (#PCDATA)>
<!ELEMENT varsta (#PCDATA)>

=== ilievladiulian/driversed/src/main/resources/xml/scoalasoferi.xml
<?xml-stylesheet type="text/xsl" href="scoalasoferi.xsl"?>
<!DOCTYPE scoalaSoferi SYSTEM "scoalasoferi.dtd">
<scoalaSoferi>
	<studenti>
		<student>
			<nume>Ilie Vlad</nume>
			<numarTelefon>0725219324</numarTelefon>
			<sex>M</sex>
			<varsta>21</varsta>
			<adresa>Bucuresti, Splaiul Independentei</adresa>
			<examen>
				<dataExamen>2013-08-20</dataExamen>
				<nota></nota>
			</examen>
			<dataInscriere>2013-05-07</dataInscriere>
			<categorie>B</categorie>
			<instructor>
				<nume>Popescu Constantin</nume>
				<numarTelefon>1423432211</numarTelefon>
				<sex>M</sex>
				<varsta>44</varsta>
				<adresa>cine mi-a mancat sarmala</adresa>
				<masina>
					<model>Opel Astra</model>
					<anFabricatie>2010</anFabricatie>
					<culoare>Negru</culoare>
					<tip>Benzina</tip>
				</masina>
			</instructor>
		</student>
		<student>
			<nume>Ionescu Viorel</nume>
			<numarTelefon>2543123412</numarTelefon>
			<sex>M</sex>
			<varsta>32</varsta>
			<adresa>ala bala portocala</adresa>
			<dataInscriere>2015-04-22</dataInscriere>
			<categorie>B</categorie>
			<instructor>
				<nume>Popescu Constantin</nume>
				<numarTelefon>1423432211</numarTelefon>
				<sex>M</sex>
				<varsta>44</varsta>
				<adresa>cine mi-a mancat sarmala</adresa>
				<masina>
					<model>Opel Astra</model>
					<anFabricatie>2010</anFabricatie>
					<culoare>Negru</culoare>
					<tip>Benzina</tip>
				</masina>
			</instructor>
		</student>
	</studenti>
	<informatie>
		<nume>ABC Auto</nume>
		<dataDeschidere>2001-03-12</dataDeschidere>
	</informatie>
</scoalaSoferi>

<!-- De bagat instructor in student -->
